---
name: idr0037-vigilante-hipsci/screenA
version: 1

defaults:
  # Should the column be processed when creating bulk-annotations (yes/no)
  include: false
  # Columns type of the bulk-annotations column
  type: string

  # If non-empty a string used to separate multiple fields in a column
  # White space will be stripped
  split:
  # Should this column be included in the clients (yes/no)
  includeclient: true
  # Should this column be visible in the clients, if no the column should be
  # hidden in the client but will still be indexed by the searcher (yes/no)
  visible: true
  # Should empty values be omitted from the client display
  omitempty: true

columns:

  - name: Comment [Operetta Plate Name]
    clientname: Operetta Plate Name
    include: true
  - name: Comment [Operetta Measurement]
    clientname: Operetta Measurement
    include: true

  - name: Control Type
    include: true
  - name: Control Comments
    include: true

  - name: Channels
    include: true
  - name: Comments
    include: true

  - name: Results Measurements
    include: true
  - name: Results Summary
    include: true

  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism]
          clientname: Organism
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/cell_line
      columns:
        - name: Characteristics [Cell Line]
          clientname: Cell Line
          include: true
        - name: Characteristics [Cell Line]
          clientname: Cell Line URL
          clientvalue: >-
            http://www.hipsci.org/lines/#/lines/{{ value|urlencode }}
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/cell_line/supplementary
      columns:
        - name: Comment [BioSamples Identifier]
          clientname: BioSamples Identifier
          include: true
        - name: Comment [BioSamples Identifier]
          clientname: BioSamples Identifier URL
          clientvalue: >
            https://www.ebi.ac.uk/biosamples/samples/{{ value|urlencode }}
          include: true
        - name: Characteristics [Cell Type]
          clientname: Cell Type
          include: true
        - name: Characteristics [Progenitor Cell Type]
          clientname: Progenitor Cell Type
          include: true
        - name: Characteristics [Donor Identifier]
          clientname: Donor Identifier
          include: true
        - name: Characteristics [Sex]
          clientname: Sex
          include: true
        - name: Characteristics [Age]
          clientname: Age
          include: true
        - name: Characteristics [Disease State]
          clientname: Disease State
          include: true
        - name: Characteristics [Ethnicity]
          clientname: Ethnicity
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/compound
      columns:
        - name: Experimental Condition [Compound]
          clientname: Compound Name
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/compound/supplementary
      columns:
        - name: Comment [ChEMBL Identifier]
          clientname: ChEMBL Identifier
          include: true
        - name: Comment [ChEMBL Identifier]
          clientname: ChEMBL Identifier URL
          clientvalue: >
            https://www.ebi.ac.uk/chembldb/target/inspect/{{ value|urlencode }}
          include: true
        - name: Experimental Condition [Dose]
          clientname: Dose
          include: true

# Advanced options (experimental)
advanced:
  # If a map-annotation is attached to a well also attach it to all images
  # in the well
  well_to_images: true

  # TODO: Primary key config should be in a global config
  ignore_missing_primary_key: true
  primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
        - Organism
    - namespace: openmicroscopy.org/mapr/cell_line
      keys:
        - Cell Line
    - namespace: openmicroscopy.org/mapr/compound
      keys:
        - Compound Name
